### ISSUE TITLE
review use of early return

### ISSUE THREAD

**Issue by BenGriffith** [BenGriffith/tollway-traffic-cloud-functions#18]
could do an early return, but that might be just my preference

_Originally posted by @bbelderbos in https://github.com/BenGriffith/tollway-traffic-cloud-functions/pull/13#discussion_r1569023430_

**Comment by BenGriffith** [comment]
![Image](https://github.com/BenGriffith/tollway-traffic-cloud-functions/assets/6089155/528df94e-2589-4321-9007-81a8e249a8de)

**Comment by bbelderbos** [comment]
cool
