### ISSUE TITLE
develop cloud function

### ISSUE THREAD

**Issue by BenGriffith** [BenGriffith/tollway-traffic-cloud-functions#3]

**Comment by BenGriffith** [comment]
1. cloud function to write to redis
2. cloud function writes events to file in GCS and at a specified time interval or size threshold another event dumps into BigQuery?

**Comment by BenGriffith** [comment]
message will be published to push subscription that will trigger cloud function and process/route message to redis

**Comment by BenGriffith** [comment]
- [x] update terraform script - redis instance is created before cloud function so that host/port can be accessed in cloud function
- [x] update function for message writes to redis

**Comment by BenGriffith** [comment]
![Image](https://github.com/BenGriffith/tollway-traffic-cloud-functions/assets/6089155/1477ea66-e92d-4a12-bb8a-cc403438f651)

purpose of screenshot is to show host information that is being created by Terraform is being passed/accessible in Cloud Function

**Comment by BenGriffith** [comment]
<img width="1022" alt="Screenshot 2024-03-29 at 8 26 29 AM" src="https://github.com/BenGriffith/tollway-traffic-cloud-functions/assets/6089155/61f667f0-04a4-4813-98f7-27a671f36e60">



![Image](https://github.com/BenGriffith/tollway-traffic-cloud-functions/assets/6089155/b349bd42-a4e4-4dbd-bdac-afcac78b902a)



after setting up VPC connector, Cloud Function is able to communicate/write to Redis

**Comment by bbelderbos** [comment]
Great work.
